"""Creation4

Revision ID: 7bdf1173a2b7
Revises: ece92e995172
Create Date: 2023-06-17 13:49:22.576001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bdf1173a2b7'
down_revision = 'ece92e995172'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'album')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('album', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
