"""Creation2

Revision ID: cfd790f72aa5
Revises: fd7e57121e8b
Create Date: 2023-06-17 13:30:18.435947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfd790f72aa5'
down_revision = 'fd7e57121e8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('album', sa.Integer(), nullable=True),
    sa.Column('ratings', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author')
    )
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('song', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song'], ['song.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('songs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price_frac', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='songs_pkey'),
    sa.UniqueConstraint('author', name='songs_author_key')
    )
    op.drop_table('playlist')
    op.drop_table('song')
    # ### end Alembic commands ###
