"""Creation3

Revision ID: ece92e995172
Revises: cfd790f72aa5
Create Date: 2023-06-17 13:47:06.865358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece92e995172'
down_revision = 'cfd790f72aa5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('songs', sa.Integer(), nullable=True))
    op.drop_constraint('playlist_song_fkey', 'playlist', type_='foreignkey')
    op.create_foreign_key(None, 'playlist', 'song', ['songs'], ['id'])
    op.drop_column('playlist', 'song')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('song', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'playlist', type_='foreignkey')
    op.create_foreign_key('playlist_song_fkey', 'playlist', 'song', ['song'], ['id'])
    op.drop_column('playlist', 'songs')
    # ### end Alembic commands ###
