"""refactor processing

Revision ID: ec77cce14ea2
Revises: 74c4c6ea4748
Create Date: 2023-05-28 17:42:30.518636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec77cce14ea2'
down_revision = '74c4c6ea4748'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('price_int', sa.Integer(), nullable=True))
    op.add_column('dish', sa.Column('price_frac', sa.Integer(), nullable=True))
    op.drop_column('dish', 'price')
    op.add_column('order_dish', sa.Column('price_int', sa.Integer(), nullable=False))
    op.add_column('order_dish', sa.Column('price_frac', sa.Integer(), nullable=False))
    op.drop_column('order_dish', 'price')
    op.alter_column('session', 'user_id', existing_type=sa.INTEGER(), nullable=False)
    op.create_foreign_key(None, 'session', 'user', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.alter_column('session', 'user_id', existing_type=sa.INTEGER(), nullable=False)
    op.add_column('order_dish', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('order_dish', 'price_frac')
    op.drop_column('order_dish', 'price_int')
    op.add_column('dish', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('dish', 'price_frac')
    op.drop_column('dish', 'price_int')
    # ### end Alembic commands ###
